### ISSUE TITLE
Differentiated Content

### ISSUE THREAD

**Issue by lauriemarkle** [IDEMSInternational/plh-facilitator-app-content#12]
As a Facilitator, I should be able to select a "package" of materials in my user profile that I want to share (i.e. what programme I'm in). This could be content differentiated based on my role within a training programme (for example, a coach could use the app to train / support a group of facilitators) or the localised needs of my programme (some provinces in Malaysia focus on parents of children ages 2-9, others on teens).

**Comment by esmeetewinkel** [comment]
Notes on content packages for Malaysia: 
1. KEMAS (i.e. public pre-school only accessible to ethnically Malay people)
   4 content packages (Group A B C D)
2. NGO / Non-profit / civil society organisations (i.e. pre-schools that Chinese and Indian people can access)
   3 content packages

Dropdowns in forms should depend on selected content package
