### ISSUE TITLE
Share-to-Socials x5

### ISSUE THREAD

**Issue by lauriemarkle** [IDEMSInternational/plh-facilitator-app-content#28]
When sharing to socials for the main message of each topic, there should be up to 5 messages shared. 
Please update the data list and web preview accordingly.

**Comment by lauriemarkle** [comment]
The feature of sharing should also include sharing attachments / assets, such as .MP4 or .MP3 files, or text.

**Comment by esmeetewinkel** [comment]
Up to five messages - done
Sharing attachments - this is now possible technically (PR https://github.com/IDEMSInternational/parenting-app-ui/pull/2160) so only thing pending is to agree which syntax / column headers we want for this

**Comment by esmeetewinkel** [comment]
Created a follow up issue for the attachments request #51, closing this
