### ISSUE TITLE
Asset Download

### ISSUE THREAD

**Issue by lauriemarkle** [IDEMSInternational/plh-facilitator-app-content#31]
As a facilitator, I want to be able to download the multimedia files such as PDF from the app so that I can easily access the materials even when offline as it creates efficiency and is less time-consuming when preparing for a session.

All media files (PDF, video, audio) should be displayed with an option to download onto the device.

**Comment by esmeetewinkel** [comment]
See dev issue [here](https://github.com/IDEMSInternational/parenting-app-ui/issues/2064)

**Comment by esmeetewinkel** [comment]
Completed 
<img width="230" alt="image" src="https://github.com/IDEMSInternational/plh-facilitator-app-content/assets/74557272/a0e5e882-547c-4333-95e2-7c4d411f56e4">
