### ISSUE TITLE
Article Image Displace on Homepage

### ISSUE THREAD

**Issue by lauriemarkle** [IDEMSInternational/plh-facilitator-app-content#36]
<img width="711" alt="image" src="https://github.com/IDEMSInternational/plh-facilitator-app-content/assets/74552270/b176b078-39b8-40ba-ac69-a1cb3adb31dd">
Article images should be displayed with the same dimensions. Right now, they are inconsistently displayed and I'm unable to determine why. 
Please also document the specs for article image icons.

**Comment by esmeetewinkel** [comment]
@lauriemarkle They are displayed with different heights (but all the same width) because the original images have different height/width ratios. I think this would look best if the images all had the same ratios. Or would you propose something else?

**Comment by lauriemarkle** [comment]
@esmeetewinkel - You're right. Sorry. I didn't realise Deepali had cropped the illustrations into different sizes. I will update and notify you when ready. Thanks!
