### ISSUE TITLE
External Hyperlinks in Web Access should Open New Tab

### ISSUE THREAD

**Issue by lauriemarkle** [IDEMSInternational/plh-facilitator-app-content#37]
When hyperlinks are added via Markdown or plain text in the data list and viewed in a web version of the app, they should open in a new tab. 

As an example, [this article contains a lot of links](https://plh-facilitator-my.web.app/template/article_how_to_report_abuse?nav_parent=article_after_disclosed_abuse&nav_parent_triggered_by=related_article_button_1), because we're building in an environment where we have Apple phone users, many users will be taking advantage of the web preview for the app in Malaysia. In this instance, we need hyperlinks to open in a new tab. The data list reads Markdown, not HTML, so I cannot write _blank to open in a new tab.

**Comment by esmeetewinkel** [comment]
Resolved by https://github.com/IDEMSInternational/parenting-app-ui/pull/2102
