### ISSUE TITLE
Files missing title field in template for Resources

### ISSUE THREAD

**Issue by lauriemarkle** [IDEMSInternational/plh-facilitator-app-content#40]
![Screenshot_20231102-144624](https://github.com/IDEMSInternational/plh-facilitator-app-content/assets/74552270/0a047a65-d756-4529-aba5-4e0eb1e65ab3)

The field "Resource_Title" is meant to appear underneath the resource icon. 

See figma:
![Screenshot_20231102-144958](https://github.com/IDEMSInternational/plh-facilitator-app-content/assets/74552270/c4ffacb0-4aba-4933-8888-20f5fca31836)

**Comment by esmeetewinkel** [comment]
Addressed in https://github.com/IDEMSInternational/plh-facilitator-app-my-content/pull/43
