### ISSUE TITLE
Added reporting form questions for fidelity screening

### ISSUE THREAD

**Issue by lauriemarkle** [IDEMSInternational/plh-facilitator-app-content#44]
In order to capture the fidelity of each engagement between facilitators and parents, each form requires additional check box or drop-down fields to accommodate fidelity screening. [Questions are here. ](https://docs.google.com/document/d/14JfQ_Yb84ZGofxNqfYeAH6lqHp7EOnEE9vG4q7Wyg08/edit). Not all forms are applicable to all groups, but the edits to these forms are universal. That is, there are not _different_ forms for the same event, but rather events that do-and-do-not appear for different research groups.

**Comment by esmeetewinkel** [comment]
- Changed structure of questions slightly, see doc [here](https://docs.google.com/document/d/14JfQ_Yb84ZGofxNqfYeAH6lqHp7EOnEE9vG4q7Wyg08/edit#heading=h.2y9s70a95lfm). In particular, questions need to be bold, subheaders italics, toggle texts regular. Closing report now has a flat structure. 
- One question is missing

**Comment by esmeetewinkel** [comment]
Note that the additional questions for the onboarding form are authored in the [report_onboarding](https://docs.google.com/spreadsheets/d/1-WnFzaXJfchvf-ZfFxzENTtPK_5yHy7-of1LrI4QyPA/edit#gid=1705255343) data list, and those for the closing in the [report_closing](https://docs.google.com/spreadsheets/d/1-WnFzaXJfchvf-ZfFxzENTtPK_5yHy7-of1LrI4QyPA/edit#gid=804265453) data list
