### ISSUE TITLE
Adding Custom Variables based on Tags

### ISSUE THREAD

**Issue by lauriemarkle** [IDEMSInternational/plh-facilitator-app-content#49]
In the current Facilitator App datalist structure, you can assign articles to unique tags. These tags are user groups or content packages selected at enrollment or edited in user settings. 

There is a use case in [Mexico](https://docs.google.com/spreadsheets/d/1ElqsKnRT3nYAJZ0C_in8swQNgZvVTnzedCiAMycw9Og/edit#gid=1402536899) that is valid in multiple scenarios wherein a single article, such as safeguarding, is applicable to all user groups but the contact information for the supervisor varies based on the user group of the facilitator (i.e. their tag). The data list structure should be modified in article_global to support tag-specific content for a single variable (e.g. supervisor_name) such that a facilitator in 1 state (Mexico City; cdmx_dif) receives the same article, but different contact details than their colleague in another state (Michocan; mich_dif).

**Comment by esmeetewinkel** [comment]
I would propose we add package-dependant variable(s) as extra column(s) to the tag data list, example [here](https://docs.google.com/spreadsheets/d/1ElqsKnRT3nYAJZ0C_in8swQNgZvVTnzedCiAMycw9Og/edit#gid=1402536899). 

To refer to the strings in a column with header `supervisor_contact` from anywhere else in the app, in particular, from the article data list, you would write `@data.tag[@fields.current_package].supervisor_contact`
