### ISSUE TITLE
Content Sharing

### ISSUE THREAD

**Issue by lauriemarkle** [IDEMSInternational/plh-facilitator-app-content#6]
As a facilitator, when viewing a topic page, I should read an introductory text followed by the message (or conversation prompt) for sharing. This conversation block should sit as a content element wtihin a page that includes a button for sharing. A "share" copies the text for pasting within available messaging apps installed on the device. 

<img width="345" alt="image" src="https://github.com/IDEMSInternational/plh-facilitator-app-content/assets/74552270/b672661e-e6d6-4424-8015-460eca14f45e">

**Comment by esmeetewinkel** [comment]
This is being addressed in https://github.com/IDEMSInternational/parenting-app-ui/issues/1925

**Comment by lauriemarkle** [comment]
@esmeetewinkel - I reviewed the FAQ format in the ParentChat manuals. A few important discoveries: 

- We want to be able to add multiple messages to share _before_ the FAQs begin. A topic might have anywhere from 1-4 questions posed to parents. 
- We will need a single page on safeguarding. This could be a subpage that appears on the home screen and include a button link on each article page. 
- The FAQs will not be plentiful, but they will differ by topic area, therefore put them in the module data list, not on their own sheet.
