### ISSUE TITLE
Topic / Content Repository

### ISSUE THREAD

**Issue by lauriemarkle** [IDEMSInternational/plh-facilitator-app-content#7]
The app has two primary functions: to offer a library of conversation topics for sharing with guidance / support and attendance reporting. The library should offer a display of available topics with two parent levels of content organization available. 

A library page with a single parent level might look like this: 
<img width="269" alt="image" src="https://github.com/IDEMSInternational/plh-facilitator-app-content/assets/74552270/e2832f2e-a795-4b92-854d-2bb8ec2f38af">

An individual content page might look like this: 
<img width="345" alt="image" src="https://github.com/IDEMSInternational/plh-facilitator-app-content/assets/74552270/4aa8416a-9e3e-4eba-94a2-f1fb930d0acd">

Content authoring should rely on headers within a Google Doc to create complete content packages for transfer.

**Comment by esmeetewinkel** [comment]
Notes from discussion 06/06/2023: 

3 sections on footer should be 
1. ODK forms (currently these will be attendance forms, but should be able to have multiple kinds of forms)
Main purpose is submitting new ODK forms, could also direct to editing previously submitted forms and setting your groups
2. Manual content (home)
3. Profile
See your user ID with ability to share, set language, define your groups + participants which would populate your attendance forms by default, enabling cleaner data collection, edit previously submitted forms

We will also want the ability to download the full PDF manual. Happy for this to be a hyperlink to the file which is stored online.

**Comment by esmeetewinkel** [comment]
@lauriemarkle I've spent some time on this, you can start populating the sheets
- [Articles](https://docs.google.com/spreadsheets/d/1YR3M1ey5xynGbq2ii6HC-v_y4SsGgN9OmPJf8Uxdztc/edit#gid=335640558): `article_data` and `article_global`
- [Navigation](https://docs.google.com/spreadsheets/d/1yzVjAHFbHuSuZAEvf16SDQHuiHNLfv5oBiLUON6h414/edit#gid=335640558): `app_section_data` and `app_menu_global`

**Comment by lauriemarkle** [comment]
@esmeetewinkel I've put content in from 2 days of the current ParentChat manual to test it out. I ran into a few challenges (like a need for a table, which I've tried using markup for) and I think we'll want the option to include some explanatory text with the message to guide the facilitator. Something like an extra column in the data list that appears in grayed italics under the shared message to explain to the facilitator any relevant details, such as "wait for parents to respond."
